const lang = {
    en: {
        search: "Search",
        gptSearchPlaceholder: "What Would You Like To Watch Today...",
        signIn: "Sign In",
        signUp: "Sign Up",
        signInNow: "Sign In Now.",
        signUpNow: "Sign Up Now.",
        newToNetflix: "New to Netflix?",
        alreadyRegister: "Already Registred?",
        emailPlaceholder: "Email",
        passwordPlaceholder: "Password",
        fnmPlaceholder: "Full Name",
        enjoyOnTV: "Enjoy on your TV",
        enjoyOnTVDetail: "Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.",
        download: "Download your shows to watch offline",
        downloadOn: "Downloading...",
        downloadDetail: "Save your favourites easily and always have something to watch.",
        watchEverywhere: "Watch everywhere",
        watchDetail: "Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.",
        child: "Create profiles for kids",
        childDetail: "Send children on adventures with their favourite characters in a space made just for them—free with your membership.",
        question: "Frequently Asked Questions",
        q1: "What is Netflix?",
        q1Answer1: "Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries and more – on thousands of internet-connected devices",
        q1Answer2: "You can watch as much as you want, whenever you want, without a single ad – all for one low monthly price. There's always something new to discover, and new TV shows and movies are added every week!",
        q2: "How much does Netflix cost?",
        q2Answer1: "Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. Plans range from ₹149 to ₹649 a month. No extra costs, no contracts.",
        q3: "Where can I watch?",
        q3Answer1: "Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.",
        q3Answer2: "You can also download your favourite shows with the iOS or Android app. Use downloads to watch while you're on the go and without an internet connection. Take Netflix with you anywhere.",
        q4: "How do I cancel?",
        q4Answer1: "Netflix is flexible. There are no annoying contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.",
        q5: "What can I watch on Netflix?",
        q5Answer1: "Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.",
        q6: "Is Netflix good for kids?",
        q6Answer1: "The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and films in their own space.",
        q6Answer2: "Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don’t want kids to see.",
        membership: "Ready to watch? Enter your email or mobile number to create or restart your membership.",
        email: "Email or Mobile Number",
        getStart: "Get Started",
        IR: "Investor Relations",
        Privacy: "Privacy",
        STest: "Speed Test",
        NI: "Netflix India",
        HC: "Help Center",
        jobs: "Jobs",
        cookie: "Cookies Prefrence",
        LNotice: "Legal Noties",
        Account: "Account",
        WTW: "Ways to Watch",
        CI: "Corporate Information",
        OoN: "Only on Netflix",
        MC: "Media Center",
        ToU: "Terma of Use",
        CU: "Contact Us",

    },
    hindi: {
        search: "खोज",
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे...",
        signIn: "साइन इन करें",
        signUp: "साइन अप करें",
        signInNow: "अभी साइन इन करें.",
        signUpNow: "अभी साइन अप करें.",
        newToNetflix: "Netflix पर नए हैं?",
        alreadyRegister: "पहले से ही हैं?",
        emailPlaceholder: "ईमेल",
        passwordPlaceholder: "पासवर्ड",
        fnmPlaceholder: "पूरा नाम",
        enjoyOnTV: "अपने टीवी पर आनंद लें",
        enjoyOnTVDetail: "स्मार्ट टीवी, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray प्लेयर के साथ ही दूसरे डिवाइस पर भी देखें.",
        download: "ऑफ़लाइन देखने के लिए अपने शो डाउनलोड करें",
        downloadOn: "डाउनलोड हो रहा है...",
        downloadDetail: "अपने पसंदीदा शो और फ़िल्में सेव करें, ताकि आप कभी भी इन्हें देख सकें.",
        watchEverywhere: "हर जगह देखें",
        watchDetail: "बिना ज़्यादा पेमेंट किए, अपने फ़ोन, टैबलेट, लैपटॉप और टीवी पर अनलिमिटेड फ़िल्में और टीवी शो स्ट्रीम करें.",
        child: "बच्चों के लिए प्रोफ़ाइल बनाएं",
        childDetail: "बच्चों को जाने दें अपने पसंदीदा किरदारों के साथ उस रोमांचक सफ़र पर जो सिर्फ़ उनके लिए ही है - आपकी मेंबरशिप के साथ फ़्री.",
        question: "अक्सर पूछे जाने वाले सवाल",
        q1: "Netflix क्या है?",
        q1Answer1: "Netflix एक स्ट्रीमिंग सर्विस है जिसके ज़रिए आप हज़ारों इंटरनेट-कनेक्टेड डिवाइस पर तरह-तरह के अवॉर्ड विजेता टीवी शो, फ़िल्में, ऐनिमे, डॉक्यूमेंट्रीज़ का लुत्फ़ उठा सकते हैं.",
        q1Answer2: "आप जब चाहें, जितना चाहें, बिना किसी विज्ञापन के देख सकते हैं – सारा कॉन्टेंट बहुत कम मासिक शुल्क पर. खोजने के लिए हमेशा कुछ नया होता है और हर हफ़्ते नए टीवी शो और फ़िल्में जोड़ी जाती हैं!",
        q2: "Netflix की कीमत कितनी है?",
        q2Answer1: "हर महीने की तय फ़ी देकर अपने स्मार्टफ़ोन, टैबलेट, स्मार्ट टीवी, लैपटॉप, या स्ट्रीमिंग डिवाइस पर Netflix देखें. हर महीने ₹149 से ₹649 तक के प्लान. कोई एक्सट्रा कीमत या कॉन्ट्रैक्ट नहीं.",
        q3: "मैं कहां देख सकता हूं?",
        q3Answer1: "कहीं भी, कभी भी देखें. तुरंत देखने के लिए वेब पर netflix.com पर जाकर अपने Netflix अकाउंट से साइन इन करें. आप Netflix ऐप ऑफ़र करने वाले इंटरनेट से जुड़े किसी भी डिवाइस से साइन इन कर सकते हैं जैसे कि आपका पर्सनल कंप्यूटर या स्मार्ट टीवी, स्मार्ट फ़ोन, टैबलेट, स्ट्रीमिंग मीडिया प्लेयर और गेम कंसोल.",
        q3Answer2: "आप iOS या Android ऐप से भी अपने पसंदीदा शो डाउनलोड कर सकते हैं. चलते-फिरते और बिना इंटरनेट कनेक्शन के देखने के लिए डाउनलोड का उपयोग करें. Netflix को अपने साथ कहीं भी ले जाएं.",
        q4: "मैं कैसे कैंसल करूं?",
        q4Answer1: "Netflix लचीला है. कोई परेशान करने वाले कॉन्ट्रैक्ट नहीं और कोई बंधन नहीं हैं. आप आसानी से दो क्लिक में अपना अकाउंट ऑनलाइन कैंसल कर सकते हैं. कोई कैंसलेशन फ़ीस नहीं है – अपना अकाउंट कभी भी शुरू या बंद करें.",
        q5: "मैं Netflix पर क्या देख सकता/सकती हूं?",
        q5Answer1: "Netflix की बहुत बड़ी लाइब्रेरी में फ़ीचर फ़िल्मों, डॉक्यूमेंट्री, टीवी शो, ऐनिमे, अवॉर्ड-विनिंग Netflix ओरिजिनल्स के अलावा और भी बहुत कुछ है. आप जितना चाहें, कभी भी देखें.",
        q6: "क्या Netflix बच्चों के लिए ठीक है?",
        q6Answer1: "आपकी मेंबरशिप में Netflix किड्स एक्सपीरियंस शामिल है. बच्चे अपनी तरह से पारिवारिक टीवी शो और फ़िल्मों का आनंद लेते हैं, लेकिन आप उनके द्वारा देखे जाने वाले कॉन्टेंट को कंट्रोल कर सकते हैं.",
        q6Answer2: "बच्चों की प्रोफ़ाइल में PIN से सुरक्षित पैरेंटल कंट्रोल्स होते हैं जिससे आप बच्चों को मेच्योरिटी रेटिंग वाले कॉन्टेंट देखने से रोक सकते हैं और उन टाइटल को ब्लॉक कर सकते हैं जिन्हें आप नहीं चाहते हैं कि बच्चे देखें.",
        membership: "देखने के लिए तैयार? अपनी मेंबरशिप बनाने या रीस्टार्ट करने के लिए अपना ईमेल एड्रेस या मोबाइल नंबर डालें.",
        email: "ईमेल या मोबाइल नंबर",
        getStart: "शुरू करें",
        IR: "इंवेस्टर संबंध",
        Privacy: "प्रायवेसी",
        STest: "स्पीड टेस्ट",
        NI: "Netflix भारत",
        HC: "सहायता केंद्र",
        jobs: "नौकरियां",
        cookie: "कुकी प्रेफ़रेंस",
        LNotice: "कानूनी सूचनाएं",
        Account: "अकाउंट",
        WTW: "देखने के तरीके",
        CI: "कॉरपोरेट जानकारी",
        OoN: "सिर्फ़ Netflix पर",
        MC: "मीडिया केंद्र",
        ToU: "उपयोग की शर्तें",
        CU: "हमसे संपर्क करें",


    },
};

export default lang;