const lang = {
    en: {
        search: "Search",
        gptSearchPlaceholder: "What Would You Like To Watch Today...",
        signIn: "Sign In",
        signUp: "Sign Up",
        signInNow: "Sign In Now.",
        signUpNow: "Sign Up Now.",
        newToNetflix: "New to Netflix?",
        alreadyRegister: "Already Registred?",
        emailPlaceholder: "Email",
        passwordPlaceholder: "Password",
        fnmPlaceholder: "Full Name",
        enjoyOnTV: "Enjoy on your TV",
        enjoyOnTVDetail: "Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.",
        download: "Download your shows to watch offline",
        downloadOn: "Downloading...",
        downloadDetail: "Save your favourites easily and always have something to watch.",
        watchEverywhere: "Watch everywhere",
        watchDetail: "Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.",
        child: "Create profiles for kids",
        childDetail: "Send children on adventures with their favourite characters in a space made just for them—free with your membership.",
    },
    hindi: {
        search: "खोज",
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे...",
        signIn: "साइन इन करें",
        signUp: "साइन अप करें",
        signInNow: "अभी साइन इन करें.",
        signUpNow: "अभी साइन अप करें.",
        newToNetflix: "Netflix पर नए हैं?",
        alreadyRegister: "पहले से ही हैं?",
        emailPlaceholder: "ईमेल",
        passwordPlaceholder: "पासवर्ड",
        fnmPlaceholder: "पूरा नाम",
        enjoyOnTV: "अपने टीवी पर आनंद लें",
        enjoyOnTVDetail: "स्मार्ट टीवी, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray प्लेयर के साथ ही दूसरे डिवाइस पर भी देखें.",
        download: "ऑफ़लाइन देखने के लिए अपने शो डाउनलोड करें",
        downloadOn: "डाउनलोड हो रहा है...",
        downloadDetail: "अपने पसंदीदा शो और फ़िल्में सेव करें, ताकि आप कभी भी इन्हें देख सकें.",
        watchEverywhere: "हर जगह देखें",
        watchDetail: "बिना ज़्यादा पेमेंट किए, अपने फ़ोन, टैबलेट, लैपटॉप और टीवी पर अनलिमिटेड फ़िल्में और टीवी शो स्ट्रीम करें.",
        child: "बच्चों के लिए प्रोफ़ाइल बनाएं",
        childDetail: "बच्चों को जाने दें अपने पसंदीदा किरदारों के साथ उस रोमांचक सफ़र पर जो सिर्फ़ उनके लिए ही है - आपकी मेंबरशिप के साथ फ़्री.",
    },
};

export default lang;